# Generated by Django 6.0.6 on 2026-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
