# Generated by Django 6.0.6 on 2026-07-04 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('order_update', 'Order Update'), ('new_order', 'New Order'), ('points_earned', 'Points Earned'), ('mission_completed', 'Mission Completed'), ('reward_redeemed', 'Reward Redeemed'), ('punch_card_completed', 'Punch Card Completed'), ('special_offer', 'Special Offer'), ('generic', 'General')], default='generic', max_length=30)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('context_url', models.CharField(blank=True, max_length=500)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('merchant_id', models.IntegerField(blank=True, null=True)),
                ('reward_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
