# Generated by Django 6.0.6 on 2026-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_awarded',
            field=models.BooleanField(default=False, help_text='True once merchant-scoped loyalty has been credited on completion.'),
        ),
    ]
