# Generated by Django 6.0.6 on 2026-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_merchant_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reward_order',
            field=models.BooleanField(default=False, help_text='True if this order was auto-created from a reward redemption.'),
        ),
    ]
