# Generated by Django 6.0.6 on 2026-07-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_reward_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_reward_order',
        ),
    ]
