# Generated by Django 6.0.6 on 2026-07-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_add_redemption_cancel_proof_fields'),
        ('orders', '0004_remove_order_is_reward_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('customer_request', 'Customer Request'), ('out_of_stock', 'Out of Stock'), ('store_closing', 'Store Closing'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('merchant', 'Merchant')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('reward_redeem', 'Reward Redemption'), ('punch_card_redeem', 'Punch Card Redemption')], db_index=True, default='regular', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='source_punch_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_order', to='loyalty.customerpunchcard'),
        ),
        migrations.AddField(
            model_name='order',
            name='source_redemption',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_order', to='loyalty.redemption'),
        ),
    ]
