# Generated by Django 6.0.6 on 2026-07-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0011_remove_merchantpunchcard_linked_menu_item_and_more'),
        ('orders', '0005_add_redemption_cancel_proof_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='source_punch_card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='source_redemption',
        ),
        migrations.AddField(
            model_name='order',
            name='punch_card_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_orders', to='loyalty.customerpunchcard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('customer_request', 'Customer Request'), ('out_of_stock', 'Out of Stock'), ('store_closing', 'Store Closing'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='loyalty_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('punch_card_redemption', 'Punch Card Redemption'), ('reward_redemption', 'Reward Redemption')], default='regular', max_length=30),
        ),
    ]
