# Generated by Django 6.0.6 on 2026-07-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0011_remove_merchantpunchcard_linked_menu_item_and_more'),
        ('orders', '0006_remove_order_source_punch_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reward_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='loyalty.redemption'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('punch_card_redemption', 'Punch Card Redemption'), ('reward_redemption', 'Reward Redemption')], db_index=True, default='regular', max_length=30),
        ),
    ]
