# Generated by Django 6.0.6 on 2026-07-11 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchantprofile_allow_delivery_and_more'),
        ('orders', '0007_order_reward_redemption_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], db_index=True, default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='merchants.merchanttable'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Preserved table name for historical reference', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number_snapshot',
            field=models.PositiveIntegerField(blank=True, help_text='Preserved table number for historical reference', null=True),
        ),
    ]
