# Generated by Django 6.0.6 on 2026-07-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_fulfillment_type_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reward_order',
            field=models.BooleanField(default=False),
        ),
    ]
