# Generated by Django 6.0.6 on 2026-07-16 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_transfer_code'),
        ('orders', '0009_add_is_reward_order_to_model'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_shift',
            field=models.ForeignKey(blank=True, help_text='Cash shift during which this order was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.cashshift'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_created_at',
            field=models.DateTimeField(blank=True, help_text='Client-side timestamp for offline orders', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_mutation_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Idempotency key for offline sync', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated discount applied to subtotal', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(blank=True, default='', help_text='fixed or percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount or percentage value', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='Primary payment method for this order', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(db_index=True, default='unpaid', help_text='unpaid, paid, partially_paid, refunded', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_device',
            field=models.ForeignKey(blank=True, help_text='POS device that created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.posdevice'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by_worker',
            field=models.ForeignKey(blank=True, help_text='POS worker who processed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.shiftworker'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('customer_app', 'Customer App'), ('table_qr', 'Table QR'), ('merchant_dashboard', 'Merchant Dashboard'), ('pos_online', 'POS Online'), ('pos_offline', 'POS Offline')], db_index=True, default='customer_app', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_origin',
            field=models.CharField(blank=True, default='', help_text='Origin of the order for sync tracking', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Increments on every update for conflict detection'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customerprofile'),
        ),
    ]
