# Generated by Django 6.0.6 on 2026-07-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_debit_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kot_number',
            field=models.PositiveIntegerField(blank=True, help_text='Kitchen Order Ticket number (sequential per merchant)', null=True),
        ),
    ]
