# Generated by Django 6.0.6 on 2026-07-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_add_kot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Guest name at time of order (preserved for historical reference)', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_session_id',
            field=models.CharField(blank=True, default='', help_text='Client-generated UUID for guest session (for future guest→member conversion)', max_length=64),
        ),
    ]
