# Generated by Django 6.0.6 on 2026-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='emoji',
            field=models.CharField(default='☕', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='points_per_item',
            field=models.IntegerField(default=1),
        ),
    ]
