# Generated by Django 6.0.6 on 2026-06-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='store_name',
            field=models.CharField(db_column='store_name', max_length=255),
        ),
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='store_name',
            new_name='business_name',
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='store_slug',
            field=models.SlugField(db_column='store_slug', unique=True),
        ),
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='store_slug',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
    ]
