# Generated by Django 6.0.6 on 2026-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_merchantprofile_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='store_theme_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for customer store view, e.g. #1e293b', max_length=7),
        ),
    ]
