# Generated by Django 6.0.6 on 2026-07-11 17:02

import django.db.models.deletion
import merchants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_add_store_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='allow_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='allow_dine_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='allow_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='table_ordering_enabled',
            field=models.BooleanField(default=False, help_text='Enable table-based ordering for dine-in customers'),
        ),
        migrations.CreateModel(
            name='MerchantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User-facing label, e.g. 'Table 4', 'Patio A', 'VIP Lounge'", max_length=100)),
                ('table_number', models.PositiveIntegerField(help_text='Numeric ordering label for sorting')),
                ('public_token', models.CharField(default=merchants.models._generate_table_token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'merchant_tables',
                'ordering': ['table_number'],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'table_number'), name='unique_table_number_per_merchant')],
            },
        ),
    ]
