# Generated by Django 6.0.6 on 2026-07-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchantprofile_allow_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='allow_point_transfer',
            field=models.BooleanField(default=False, help_text='Allow customers to transfer points to other members of this business'),
        ),
    ]
