# Generated by Django 6.0.6 on 2026-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_merchantprofile_allow_point_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='credit_accounts_enabled',
            field=models.BooleanField(default=False, help_text='Allow customers to purchase on credit'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='discounts_enabled',
            field=models.BooleanField(default=False, help_text='Allow staff to apply discounts at POS'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='manager_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount above which manager approval is required', max_digits=10),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='max_worker_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum discount percentage a worker can apply without manager approval', max_digits=5),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='offline_credit_allowed',
            field=models.BooleanField(default=False, help_text='Allow credit sales while offline'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='offline_discounts_allowed',
            field=models.BooleanField(default=False, help_text='Allow applying discounts while offline'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='offline_pos_enabled',
            field=models.BooleanField(default=False, help_text='Allow POS to queue orders offline and sync later'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='pos_enabled',
            field=models.BooleanField(default=False, help_text='Enable the Point of Sale system for this merchant'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='receipt_printing_enabled',
            field=models.BooleanField(default=False, help_text='Enable receipt printing from POS'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='shift_management_enabled',
            field=models.BooleanField(default=False, help_text='Require cash shifts for POS operations'),
        ),
    ]
