# Generated by Django 6.0.6 on 2026-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_merchantprofile_credit_accounts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='debit_accounts_enabled',
            field=models.BooleanField(default=False, help_text='Enable prepaid debit accounts (customer wallet / stored value)'),
        ),
    ]
