# Generated by Django 6.0.6 on 2026-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0007_add_debit_accounts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='card_background_image',
            field=models.URLField(blank=True, default='', help_text='Background image URL for the customer loyalty card'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='card_text_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for loyalty card text, e.g. #ffffff', max_length=7),
        ),
    ]
