# Generated by Django 6.0.6 on 2026-07-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_add_card_text_color_and_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='listing_card_bg',
            field=models.CharField(blank=True, default='', help_text='Background color for the store listing card, e.g. #FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='listing_card_text_color',
            field=models.CharField(blank=True, default='', help_text='Text color for the store listing card, e.g. #1A1A1A', max_length=7),
        ),
    ]
