# Generated by Django 6.0.6 on 2026-07-16 09:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customerprofile_transfer_code'),
        ('merchants', '0006_merchantprofile_credit_accounts_enabled_and_more'),
        ('orders', '0009_add_is_reward_order_to_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, default='', help_text='Name for walk-in credit customers without a customer profile', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Null for walk-in credit accounts identified by name/phone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'pos_credit_accounts',
            },
        ),
        migrations.CreateModel(
            name='PosDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable device name, e.g. 'Front Counter Terminal'", max_length=120)),
                ('device_token_hash', models.CharField(help_text='SHA-256 hash of the device registration token', max_length=255)),
                ('platform', models.CharField(blank=True, default='', help_text="Device platform, e.g. 'ios', 'android', 'windows'", max_length=100)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_devices', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'pos_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_other_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('conflict', 'Conflict')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='synced', help_text='synced, pending, syncing, failed, conflict', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='merchants.merchantprofile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_shifts', to='pos.posdevice')),
            ],
            options={
                'db_table': 'pos_shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('pin_hash', models.CharField(help_text='SHA-256 hash of the worker PIN', max_length=255)),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('waiter', 'Waiter'), ('manager', 'Manager'), ('admin', 'Admin')], default='cashier', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('can_apply_discount', models.BooleanField(default=False)),
                ('can_process_refund', models.BooleanField(default=False)),
                ('can_close_shift', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('failed_pin_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_workers', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'pos_workers',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PosPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_qr', 'Bank QR'), ('mobile_wallet', 'Mobile Wallet'), ('credit', 'Credit'), ('split', 'Split'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, default='', help_text='Gateway or provider reference for digital payments', max_length=255)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cash change given back to customer', max_digits=12)),
                ('client_mutation_id', models.UUIDField(help_text='Idempotency key for offline sync', unique=True)),
                ('client_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(default='synced', help_text='synced, pending, syncing, failed, conflict', max_length=20)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.posdevice')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_payments', to='merchants.merchantprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_payments', to='orders.order')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.cashshift')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'pos_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage value', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Calculated discount amount applied to the order', max_digits=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_discounts', to='merchants.merchantprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_discounts', to='orders.order')),
                ('authorized_by', models.ForeignKey(blank=True, help_text='Manager who authorized this discount (if required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_authorized', to='pos.shiftworker')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_applied', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'pos_discounts',
            },
        ),
        migrations.CreateModel(
            name='PosAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('device_register', 'Device Register'), ('device_deactivate', 'Device Deactivate'), ('worker_login', 'Worker Login'), ('worker_logout', 'Worker Logout'), ('worker_create', 'Worker Create'), ('worker_update', 'Worker Update'), ('shift_open', 'Shift Open'), ('shift_close', 'Shift Close'), ('order_create', 'Order Create'), ('order_update', 'Order Update'), ('order_cancel', 'Order Cancel'), ('discount_apply', 'Discount Apply'), ('payment', 'Payment'), ('refund', 'Refund'), ('credit_sale', 'Credit Sale'), ('credit_repay', 'Credit Repay'), ('sync_attempt', 'Sync Attempt'), ('sync_conflict', 'Sync Conflict'), ('sync_resolve', 'Sync Resolve'), ('report_generate', 'Report Generate'), ('merchant_login', 'Merchant Login')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_audit_logs', to='merchants.merchantprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.posdevice')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'pos_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('repayment', 'Repayment'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('client_mutation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(default='synced', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.creditaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='orders.order')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'pos_credit_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cashshift',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to='pos.shiftworker'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_shifts', to='pos.shiftworker'),
        ),
        migrations.CreateModel(
            name='ProcessedClientMutation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_mutation_id', models.UUIDField()),
                ('entity_type', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=50)),
                ('server_object_id', models.UUIDField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_mutations', to='pos.posdevice')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_mutations', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'pos_processed_mutations',
                'constraints': [models.UniqueConstraint(fields=('merchant', 'device', 'client_mutation_id'), name='unique_pos_client_mutation')],
            },
        ),
    ]
