# Generated by Django 6.0.6 on 2026-07-16 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_transfer_code'),
        ('merchants', '0007_add_debit_accounts_enabled'),
        ('orders', '0013_add_debit_accounts'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posauditlog',
            name='action',
            field=models.CharField(choices=[('device_register', 'Device Register'), ('device_deactivate', 'Device Deactivate'), ('worker_login', 'Worker Login'), ('worker_logout', 'Worker Logout'), ('worker_create', 'Worker Create'), ('worker_update', 'Worker Update'), ('shift_open', 'Shift Open'), ('shift_close', 'Shift Close'), ('order_create', 'Order Create'), ('order_update', 'Order Update'), ('order_cancel', 'Order Cancel'), ('discount_apply', 'Discount Apply'), ('payment', 'Payment'), ('refund', 'Refund'), ('credit_sale', 'Credit Sale'), ('credit_repay', 'Credit Repay'), ('debit_topup', 'Debit Top-up'), ('debit_purchase', 'Debit Purchase'), ('debit_adjustment', 'Debit Adjustment'), ('sync_attempt', 'Sync Attempt'), ('sync_conflict', 'Sync Conflict'), ('sync_resolve', 'Sync Resolve'), ('report_generate', 'Report Generate'), ('merchant_login', 'Merchant Login')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DebitAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, default='', help_text='Name for walk-in debit customers without a customer profile', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current stored value available to spend', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Null for walk-in debit accounts identified by name/phone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_accounts', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'pos_debit_accounts',
            },
        ),
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('topup', 'Top-up'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('client_mutation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(default='synced', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.debitaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_transactions', to='orders.order')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_transactions', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'pos_debit_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
