# Generated by Django 6.0.6 on 2026-07-17 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_add_staff_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashshift',
            name='cash_payins',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cash added to drawer during this shift (pay-ins)', max_digits=12),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='cash_payouts',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cash removed from drawer during this shift (pay-outs)', max_digits=12),
        ),
        migrations.CreateModel(
            name='PosCashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('payout', 'Pay-out (Cash removed)'), ('payin', 'Pay-in (Cash added)'), ('cashdrop', 'Cash Drop (Bank deposit)')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. Type determines direction.', max_digits=12)),
                ('reason', models.CharField(blank=True, default='', help_text='Reason for the cash movement', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='pos.cashshift')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'pos_cash_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
