# Generated by Django 6.0.6 on 2026-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_add_cash_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pospayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_qr', 'Bank QR'), ('mobile_wallet', 'Mobile Wallet'), ('credit', 'Credit'), ('debit', 'Debit'), ('split', 'Split'), ('other', 'Other')], max_length=30),
        ),
    ]
