# Generated by Django 6.0.6 on 2026-06-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_npr', models.FloatField(default=1.0)),
                ('streak_multiplier', models.FloatField(default=1.5)),
                ('welcome_bonus', models.IntegerField(default=50)),
                ('birthday_bonus', models.IntegerField(default=100)),
                ('streak_min_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rules', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'loyalty_rules',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='🎯', max_length=50)),
                ('mission_type', models.CharField(choices=[('order_count', 'Order Count'), ('spend_amount', 'Spend Amount'), ('visit_streak', 'Visit Streak'), ('purchase', 'Purchase'), ('visit', 'Visit'), ('referral', 'Referral'), ('special', 'Special')], default='order_count', max_length=20)),
                ('target_count', models.IntegerField(default=1)),
                ('reward_points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🎁', max_length=10)),
                ('points_cost', models.IntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='accounts.customerprofile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.reward')),
            ],
            options={
                'db_table': 'redemptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='accounts.customerprofile')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='loyalty.mission')),
            ],
            options={
                'db_table': 'customer_missions',
                'unique_together': {('customer', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='PunchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_count', models.IntegerField(default=0)),
                ('punches_to_free', models.IntegerField(default=5)),
                ('lifetime_punches', models.IntegerField(default=0)),
                ('free_reward_available', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_cards', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_cards', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'punch_cards',
                'unique_together': {('customer', 'merchant')},
            },
        ),
    ]
