# Generated by Django 6.0.6 on 2026-06-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loyalty', '0001_initial'),
        ('merchants', '0002_add_menuitem_points_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PunchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_count', models.IntegerField(default=0)),
                ('punches_to_free', models.IntegerField(default=5)),
                ('lifetime_punches', models.IntegerField(default=0)),
                ('free_reward_available', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_cards', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_cards', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'punch_cards',
                'unique_together': {('customer', 'merchant')},
            },
        ),
    ]
