# Generated by Django 6.0.6 on 2026-06-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loyalty', '0001_initial'),
        ('merchants', '0002_alter_merchantprofile_store_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profiles', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'customer_merchant_profiles',
                'unique_together': {('customer', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='CustomerMerchantWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('expired_points', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('last_point_earned_at', models.DateTimeField(blank=True, null=True)),
                ('tier_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_wallets', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallets', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'customer_merchant_wallets',
                'indexes': [models.Index(fields=['merchant', '-points_balance'], name='customer_me_merchan_7d2225_idx')],
                'unique_together': {('customer', 'merchant')},
            },
        ),
    ]
