# Generated by Django 6.0.6 on 2026-06-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loyalty', '0002_merchant_wallets'),
        ('merchants', '0002_alter_merchantprofile_store_name_and_more'),
        ('orders', '0002_merchant_wallets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermerchantwallet',
            name='last_order_date',
        ),
        migrations.AddField(
            model_name='customermerchantwallet',
            name='last_order_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MerchantPunchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('per_order', 'Per Order'), ('per_streak', 'Per Streak')], default='per_order', max_length=20)),
                ('stamps_required', models.IntegerField(default=5)),
                ('reward_text', models.CharField(help_text="Text description of the reward (e.g., 'Free Coffee')", max_length=255)),
                ('background_image', models.URLField(blank=True)),
                ('animated_gif_background', models.URLField(blank=True)),
                ('color_scheme', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=20)),
                ('stamp_icon', models.CharField(default='☕', help_text='Emoji or URL to stamp icon', max_length=255)),
                ('logo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_cards', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'merchant_punch_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPunchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stamps', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_cards', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_punch_cards', to='merchants.merchantprofile')),
                ('punch_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_progress', to='loyalty.merchantpunchcard')),
            ],
            options={
                'db_table': 'customer_punch_cards',
                'unique_together': {('customer', 'punch_card', 'is_completed')},
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed'), ('MISSION_BONUS', 'Mission Bonus'), ('PUNCH_CARD_REWARD', 'Punch Card Reward'), ('EXPIRED', 'Expired'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('TRANSFER_SENT', 'Transfer Sent'), ('TRANSFER_RECEIVED', 'Transfer Received')], max_length=50)),
                ('points', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='merchants.merchantprofile')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='loyalty.mission')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='orders.order')),
                ('punch_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='loyalty.customerpunchcard')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='loyalty.reward')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customermerchantwallet')),
            ],
            options={
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PunchCard',
        ),
    ]
