# Generated by Django 6.0.6 on 2026-06-29 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_remove_customermerchantwallet_last_order_date_and_more'),
        ('merchants', '0002_alter_merchantprofile_store_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaySpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specials', to='merchants.menuitem')),
                ('linked_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specials', to='loyalty.reward')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_specials', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'today_specials',
                'ordering': ['-created_at'],
            },
        ),
    ]
