# Generated by Django 6.0.6 on 2026-07-04 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_notification'),
        ('orders', '0003_order_is_reward_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption', to='orders.order'),
        ),
    ]
