# Generated by Django 6.0.6 on 2026-07-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0007_alter_redemption_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='order',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
