# Generated by Django 6.0.6 on 2026-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_remove_redemption_order_delete_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerpunchcard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='merchantpunchcard',
            name='color_scheme',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='merchantpunchcard',
            name='reward_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='merchantpunchcard',
            name='stamp_icon',
            field=models.CharField(default='☕', max_length=255),
        ),
    ]
