# Generated by Django 6.0.6 on 2026-07-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_alter_customerpunchcard_unique_together_and_more'),
        ('merchants', '0002_alter_merchantprofile_store_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpunchcard',
            name='proof_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customerpunchcard',
            name='proof_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpunchcard',
            name='proof_code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantpunchcard',
            name='linked_menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_card_rewards', to='merchants.menuitem'),
        ),
        migrations.AddField(
            model_name='reward',
            name='linked_menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_items', to='merchants.menuitem'),
        ),
    ]
