# Generated by Django 6.0.6 on 2026-07-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_add_redemption_cancel_proof_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantpunchcard',
            name='linked_menu_item',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='linked_menu_item',
        ),
        migrations.AlterField(
            model_name='customerpunchcard',
            name='proof_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
