# Generated by Django 6.0.6 on 2026-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0011_remove_merchantpunchcard_linked_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='transfer_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
