# Generated by Django 6.0.6 on 2026-07-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0012_pointtransaction_transfer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpunchcard',
            name='stamp_gif_url',
            field=models.URLField(blank=True, default='', null=True, help_text='Optional GIF URL to use instead of emoji stamp'),
        ),
    ]
