# Generated by Django 6.0.6 on 2026-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0013_add_stamp_gif_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpunchcard',
            name='animated_gif_background',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='merchantpunchcard',
            name='background_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='merchantpunchcard',
            name='logo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='merchantpunchcard',
            name='stamp_gif_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
