# Generated by Django 6.0.6 on 2026-07-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0015_add_membership_fields'),
        ('merchants', '0005_merchantprofile_allow_point_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermerchantwallet',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='loyalty.customermerchantprofile'),
        ),
        migrations.AddField(
            model_name='customermerchantwallet',
            name='redeemed_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='loyalty.customermerchantprofile'),
        ),
        migrations.CreateModel(
            name='MembershipQrToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='loyalty.customermerchantprofile')),
            ],
            options={
                'db_table': 'membership_qr_tokens',
            },
        ),
        migrations.CreateModel(
            name='MerchantMembershipCardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(default='Membership', max_length=100)),
                ('card_subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('background_type', models.CharField(choices=[('solid', 'Solid Color'), ('image', 'Image'), ('pattern', 'Pattern')], default='solid', max_length=20)),
                ('primary_color', models.CharField(default='#171717', max_length=7)),
                ('secondary_color', models.CharField(default='#382418', max_length=7)),
                ('accent_color', models.CharField(default='#D97941', max_length=7)),
                ('text_mode', models.CharField(choices=[('light', 'Light Text'), ('dark', 'Dark Text')], default='light', max_length=10)),
                ('background_image', models.URLField(blank=True, default='')),
                ('background_pattern', models.CharField(choices=[('', 'None'), ('zentro_dots', 'Zentro Dots'), ('geometric', 'Geometric'), ('diamonds', 'Diamonds')], default='zentro_dots', max_length=30)),
                ('logo', models.URLField(blank=True, default='')),
                ('tier_style', models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('badge', 'Badge')], default='default', max_length=20)),
                ('points_label', models.CharField(default='POINTS', max_length=50)),
                ('membership_label', models.CharField(default='MEMBERSHIP', max_length=50)),
                ('show_lifetime_points', models.BooleanField(default=True)),
                ('show_joined_date', models.BooleanField(default=True)),
                ('show_qr_shortcut', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_design', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'merchant_card_designs',
            },
        ),
    ]
