/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as StoresIdRouteImport } from './routes/stores_.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as MerchantStoreRouteImport } from './routes/merchant.store'
import { Route as MerchantSpecialsRouteImport } from './routes/merchant.specials'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantOnboardingRouteImport } from './routes/merchant.onboarding'
import { Route as MerchantMenuRouteImport } from './routes/merchant.menu'
import { Route as MerchantLoyaltyRouteImport } from './routes/merchant.loyalty'
import { Route as MerchantAnalyticsRouteImport } from './routes/merchant.analytics'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerOrderRouteImport } from './routes/customer.order'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthMerchantRouteImport } from './routes/auth.merchant'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as CustomerMerchantSlugRouteImport } from './routes/customer.merchant.$slug'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores_/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantStoreRoute = MerchantStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSpecialsRoute = MerchantSpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOnboardingRoute = MerchantOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLoyaltyRoute = MerchantLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAnalyticsRoute = MerchantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MerchantRoute,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrderRoute = CustomerOrderRouteImport.update({
  id: '/customer/order',
  path: '/customer/order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMerchantRoute = AuthMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const CustomerMerchantSlugRoute = CustomerMerchantSlugRouteImport.update({
  id: '/customer/merchant/$slug',
  path: '/customer/merchant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/m/$slug': typeof MSlugRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/specials': typeof MerchantSpecialsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/orders/$id': typeof OrdersIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/customer/merchant/$slug': typeof CustomerMerchantSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/m/$slug': typeof MSlugRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/specials': typeof MerchantSpecialsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/orders/$id': typeof OrdersIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/merchant': typeof MerchantIndexRoute
  '/customer/merchant/$slug': typeof CustomerMerchantSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/merchant': typeof AuthMerchantRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/m/$slug': typeof MSlugRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/specials': typeof MerchantSpecialsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/orders/$id': typeof OrdersIdRoute
  '/stores_/$id': typeof StoresIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/customer/merchant/$slug': typeof CustomerMerchantSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/merchant'
    | '/missions'
    | '/profile'
    | '/rewards'
    | '/stores'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/customer/order'
    | '/customer/orders'
    | '/m/$slug'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/onboarding'
    | '/merchant/orders'
    | '/merchant/specials'
    | '/merchant/store'
    | '/orders/$id'
    | '/stores/$id'
    | '/merchant/'
    | '/customer/merchant/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/missions'
    | '/profile'
    | '/rewards'
    | '/stores'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/customer/order'
    | '/customer/orders'
    | '/m/$slug'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/onboarding'
    | '/merchant/orders'
    | '/merchant/specials'
    | '/merchant/store'
    | '/orders/$id'
    | '/stores/$id'
    | '/merchant'
    | '/customer/merchant/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/merchant'
    | '/missions'
    | '/profile'
    | '/rewards'
    | '/stores'
    | '/auth/forgot-password'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/customer/order'
    | '/customer/orders'
    | '/m/$slug'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/onboarding'
    | '/merchant/orders'
    | '/merchant/specials'
    | '/merchant/store'
    | '/orders/$id'
    | '/stores_/$id'
    | '/merchant/'
    | '/customer/merchant/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CartRoute: typeof CartRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  StoresRoute: typeof StoresRoute
  CustomerOrderRoute: typeof CustomerOrderRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  MSlugRoute: typeof MSlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  StoresIdRoute: typeof StoresIdRoute
  CustomerMerchantSlugRoute: typeof CustomerMerchantSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/stores_/$id': {
      id: '/stores_/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/store': {
      id: '/merchant/store'
      path: '/store'
      fullPath: '/merchant/store'
      preLoaderRoute: typeof MerchantStoreRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/specials': {
      id: '/merchant/specials'
      path: '/specials'
      fullPath: '/merchant/specials'
      preLoaderRoute: typeof MerchantSpecialsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/onboarding': {
      id: '/merchant/onboarding'
      path: '/onboarding'
      fullPath: '/merchant/onboarding'
      preLoaderRoute: typeof MerchantOnboardingRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/loyalty': {
      id: '/merchant/loyalty'
      path: '/loyalty'
      fullPath: '/merchant/loyalty'
      preLoaderRoute: typeof MerchantLoyaltyRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/analytics': {
      id: '/merchant/analytics'
      path: '/analytics'
      fullPath: '/merchant/analytics'
      preLoaderRoute: typeof MerchantAnalyticsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/order': {
      id: '/customer/order'
      path: '/customer/order'
      fullPath: '/customer/order'
      preLoaderRoute: typeof CustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/merchant': {
      id: '/auth/merchant'
      path: '/merchant'
      fullPath: '/auth/merchant'
      preLoaderRoute: typeof AuthMerchantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/customer/merchant/$slug': {
      id: '/customer/merchant/$slug'
      path: '/customer/merchant/$slug'
      fullPath: '/customer/merchant/$slug'
      preLoaderRoute: typeof CustomerMerchantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMerchantRoute: typeof AuthMerchantRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMerchantRoute: AuthMerchantRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MerchantRouteChildren {
  MerchantAnalyticsRoute: typeof MerchantAnalyticsRoute
  MerchantLoyaltyRoute: typeof MerchantLoyaltyRoute
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantOnboardingRoute: typeof MerchantOnboardingRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantSpecialsRoute: typeof MerchantSpecialsRoute
  MerchantStoreRoute: typeof MerchantStoreRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantAnalyticsRoute: MerchantAnalyticsRoute,
  MerchantLoyaltyRoute: MerchantLoyaltyRoute,
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantOnboardingRoute: MerchantOnboardingRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantSpecialsRoute: MerchantSpecialsRoute,
  MerchantStoreRoute: MerchantStoreRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CartRoute: CartRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoyaltyRoute: LoyaltyRoute,
  MerchantRoute: MerchantRouteWithChildren,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  StoresRoute: StoresRoute,
  CustomerOrderRoute: CustomerOrderRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  MSlugRoute: MSlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  StoresIdRoute: StoresIdRoute,
  CustomerMerchantSlugRoute: CustomerMerchantSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
