# Generated by Django 6.0.6 on 2026-07-10 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_alter_merchantprofile_store_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('reward_confirmed', 'Reward Confirmed'), ('punch_card_confirmed', 'Punch Card Confirmed'), ('point_adjustment', 'Point Adjustment'), ('point_transfer', 'Point Transfer'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('reward_redeemed', 'Reward Redeemed')], db_index=True, max_length=50)),
                ('target_model', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='merchants.merchantprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['merchant', '-created_at'], name='audit_logs_merchan_c9d1b7_idx')],
            },
        ),
    ]
